### PR TITLE
adding hover controls to widgets demo

### PR DESCRIPTION
**Pull request by tsutterley**
add more map layers for each projection
add ability to include any layer from xyzservices
update dockerfile to add GDAL dependency
change dockerfile entry point to jupyter lab

### CODE REVIEW

**Comment by dshean** [comment]
Finally a moment to take a look at latest PR.  Looks great!

One minor thing - I find the UTC datetime string to be valuable in the tooltip.  For whatever reason, the DataFrame index value is not preserved.  I ended up adding a separate column so this would show up.  

Maybe you can figure out a more elegant way to do this, or just use a similar approach.  I tried adding the datetime string column to the gdf in the latest widget notebook before adding to map, but it didn't work out of the box.  Looks like you've specified a subset of fields to display?

**Comment by dshean** [comment]
I think we want ESRI imagery available in the dropdown for Global projection.  Not sure about ESRI imagery quality over Antarctica.  Can quickly discuss tomorrow while exploring latest functionality.

**Comment by tsutterley** [comment]
Okay I think all that's done.  I simply added another column to the dataframe called index that's the UTC time stamp in this case

**Comment by dshean** [comment]
Great!  Seems like merging this one makes sense, and we can create separate PRs for the voila deployment, and the mouseclick point selection with separate widget button to display corresponding gt profile in a new plot.

**Pull request merged**
